name    'daks-wget'
version '0.0.1'
source 'UNKNOWN'
author 'daks'
license 'Apache License, Version 2.0'
summary 'a simple module to manage wget'
description 'a simple module to manage wget'
project_page 'https://github.com/daks/puppet-wget'
